lesiontrackwebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^liverdata/', include('liverdata.urls'))
]

liverdata/urls.py
from django.conf.urls import url
from . import views

app_name = 'liverdata'

urlpatterns = [
    # /liverdata/
    url(r'^$', views.index, name='index'),
    # /liverdata/713/
    url(r'patient_list', views.patient_list, name='patient_list'),
    url(r'patient/(?P<patient_id>[0-9]+)/$', views.patient_detail, name='patient_detail'),

    # /liverdata/patientxyx/lesionxyz/
    url(r'lesion/(?P<lesion_id>[0-9]+)/$', views.lesion_detail, name='lesion_detail')
]

liverdata/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    patient_name = models.CharField(max_length=20)
    # gender = models.CharField(choices=(('F','Female'), ('M','Male')), max_length=1, blank=True)
    yearofbirth = models.PositiveIntegerField(null= True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    study_institution = models.CharField(max_length=100, default='Bern', blank=True) #optional field
    study_name = models.CharField(max_length=100, default='ClinicalStudyBern', blank=True) # optional field

    class Meta:
        ordering = ["patient_name", "patient_name"]

    def __str__(self):
        return self.patient_name



class LesionType(models.Model):
    lesiontype_name = models.CharField(max_length=50)
    lesiontype_shortname = models.CharField(max_length=5)

    def __str__(self):
        return "{0}".format(self.lesiontype_shortname)

class Lesion(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.CASCADE, blank=True, null=True)
    lesiontype = models.ForeignKey(LesionType, on_delete = models.PROTECT, null=True, blank=False) # can be non-existent, but not blank
    lesion_volume_ml = models.DecimalField(max_digits=10, decimal_places=2, blank=True) #optional field
    lesion_biopsy = models.BooleanField(default=False) # choice field, y/n
    lesion_nr = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
            ordering = ["patient", "lesion_nr"]

    def __str__(self):
        return "{0} - {1} - {2}".format(self.patient,self.lesiontype, self.lesion_nr)


class TreatmentSession(models.Model):
    patient = models.ForeignKey(Patient, on_delete = models.PROTECT, blank=True, null=True)
    treatmentsession_date = models.DateTimeField('Treatment Session Date:')
    treatment_nr = models.PositiveIntegerField() # change to blank=true, null=true
    treatment_type = models.CharField(choices=(
        ('IR', 'Intervention'),
        ('LP', 'Laparoscopy'),
        ('Open', 'Surgery'),
        ('Resection', 'Resection'),
        ('Chemotherapy', 'Chemotherapy')
        ),
        max_length=10) # intervention, laparoscopy, open, Resection

    class Meta:
        ordering = ["treatment_type", "treatmentsession_date"]

    def __str__(self):
        return "{0} - {1} - {2}".format(self.patient, self.treatment_type, self.treatmentsession_date)


class TreatmentName(models.Model):
    treatment_name = models.CharField(max_length=100)
    short_name = models.CharField(max_length=5)

    def __str__(self):
        return self.short_name

    class Meta:
        verbose_name_plural = "TreatmentName"


class Treatment(models.Model):
    treatmentsession = models.ForeignKey(TreatmentSession, on_delete = models.CASCADE)
    treatmentname = models.ForeignKey(TreatmentName, on_delete = models.PROTECT, null=True, blank=False)
    lesion = models.ForeignKey(Lesion, on_delete=models.CASCADE)

    def __str__(self):
        return  "{0} - {1} - {2}".format(self.treatmentsession.treatmentsession_date, self.treatmentname, self.lesion)



class Device(models.Model):
    manufacturer = models.CharField(max_length=200)
    needle_name = models.CharField(max_length=200)
    others = models.TextField()

    def __str__(self):
        return "{0} ({1})".format(self.manufacturer, self.needle_name)

    class Meta:
        verbose_name_plural = "Device"


class Trajectory(models.Model):
    parent_trajectory = models.ForeignKey('self', null=True, blank=True, on_delete=models.PROTECT) # recursive relationship for reference trajectory
    entrypoint_planned = models.CharField(max_length=500)
    targetpoint_planned = models.CharField(max_length=500)
    entrypoint_measured = models.CharField(max_length=500)
    targetpoint_measured = models.CharField(max_length=500)
    trajectory_nr = models.PositiveIntegerField(null=True, blank=True)


    def __str__(self):
        return "{0}-{1}".format(str(self.trajectory_nr), str(self.id))

    class Meta:
        verbose_name_plural = "Trajectory"


class TPErrors(models.Model):
    trajectory =  models.ForeignKey('Trajectory',on_delete=models.PROTECT)
    lateralerror = models.FloatField(max_length=500)
    longerror = models.FloatField(max_length=500)
    angularerror = models.FloatField(max_length=500)
    residualerror = models.FloatField(max_length=500)

    def __str__(self):
        return "residualerror = " + str(self.residualerror)

    class Meta:
        verbose_name_plural = "TPErrors"


class MWA(models.Model):
    treatment = models.OneToOneField(Treatment, blank=True, null=True, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, blank=True, null=True, on_delete=models.CASCADE)
    trajectory_id = models.OneToOneField(Trajectory, blank=True, null=True) # sholdn't be a optional relationship, modify it later
    power = models.PositiveIntegerField() # power or temperature applied
    time_duration = models.DurationField()

    def __str__(self):
        return 'TreatmentName:' + MWA.__name__

    class Meta:
        verbose_name_plural = "MWA"

class RFA(models.Model):
    treatment = models.OneToOneField(Treatment, blank=True, null=True, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, blank=True, null=True, on_delete=models.CASCADE)
    trajectory_id = models.OneToOneField(Trajectory, blank=True, null=True)
    power = models.PositiveIntegerField() # power or temperature applied
    time_duration = models.DurationField()

    def __str__(self):
        return 'Treamment Name:' + RFA.__name__

    class Meta:
        verbose_name_plural = "RFA"

class IRE(models.Model):
    treatment = models.OneToOneField(Treatment, blank=True, null=True, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, blank=True, null=True, on_delete=models.CASCADE)
    trajectory_id = models.OneToOneField(Trajectory, blank=True, null=True)
    power = models.PositiveIntegerField() # power or temperature applied
    time_duration = models.DurationField()

    def __str__(self):
        return 'TreatmentName:' +  IRE.__name__

    class Meta:
        verbose_name_plural = "IRE"

liverdata/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.template import loader
from django.views import generic
from .models import Patient, Lesion, Treatment, MWA, RFA, IRE, Trajectory, TPErrors,TreatmentSession


def index(request):
    num_patients = Patient.objects.all().count()
    num_lesions = Lesion.objects.all().count()
    num_rfa_ablations = RFA.objects.all().count()
    num_ir = TreatmentSession.objects.filter(treatment_type__exact='IR').count()
    return render(request, 'liverdata/index.html', context = {'num_patients':num_patients, 'num_lesions': num_lesions, 'num_rfa_ablations': num_rfa_ablations, 'num_ir':num_ir})

def patient_list(request):
    all_patients = Patient.objects.all()
    return render(request, 'liverdata/patient_list.html', {'all_patients' : all_patients})

def patient_detail(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    return render(request, 'liverdata/patient_detail.html', {'patient' : patient})

def lesion_detail(request, lesion_id):
    lesion = get_object_or_404(Lesion, pk=lesion_id)
    return render(request, 'liverdata/lesion_detail.html', {'lesion': lesion})

liverdata/templates/liverdata/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title> LIT </title>
  <meta charset="utf-8">
{% load bootstrap3 %} {# Load CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript %} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'liverdata/style.css'  %}" />
</head>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!--logo-->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'liverdata:index' %}">Home</a>
      </div>

      <!--Items-->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'liverdata:patient_list' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Patient View</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-record" aria-hidden="true"></span>&nbsp;Lesion View</a></li>
        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-open" aria-hidden="true"></span>&nbsp; Upload</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
        </ul>

      </div>

    </div>
  </nav>

{% block body %}
{% endblock %}
</body>
</html>

liverdata/templates/liverdata/detail.html
{# Load the tag library #} {% load bootstrap3 %} {# Load CSS and JavaScript #} {% bootstrap_css %} {% bootstrap_javascript %} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %}

{% block title %}
<h1> {{patient.patient_name}} </h1> {% endblock %}
{% block content %}
{% if patient.lesion_set.all %}
<table class="table">
  {% for lesion in patient.lesion_set.all %}
  <tr>
    <td> {{lesion.lesion_name}} - {{lesion.lesion_size}} </td>
  </tr>
  {% endfor %}
</table>
{% else %}
  <h3> No lesions are available</h3> {% endif %}
{% endblock %}

liverdata/templates/liverdata/index.html
{% extends 'liverdata/base.html' %} {% block body %} {% block title %}
<h2></h2>{% endblock %}
<div class="container-fluid patients-container">
  <div class="row content">
    <div class="col-sm-2 sidenav">

          <img src="/static/liverdata/images/hipernavLogo.png">

  </div>


    <div class="col-sm-8 text-left">&nbsp;
      <div class="jumbotron">
      <h3>Welcome to LIT - <strong>Liver Lesion Tracking</strong> - database application</h3>
      <br>
      <ul class="list_group">
        <li class="list-group-item"><strong>Number of patients: </strong>{{ num_patients}}</li>
          <li class="list-group-item"> <strong>Number of lesions:</strong>{{ num_lesions }}</li>
          <li class="list-group-item"> <strong>Number of RFA ablations:</strong>{{ num_rfa_ablations }}</li>
          <li class="list-group-item"> <strong>Number of Interventions:</strong>{{ num_ir}}</li>
      </ul>

</div>
    </div>

    <!-- <div class="col-sm-2 sidenav">
      <div class="well">
        <p></p>
      </div>
    </div> -->

    <div class="footer navbar-fixed-bottom">
      <div class="well">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-10 col-xs-12"></div>
            <div class="col-md-2 col-xs-12">
              <img src="http://www.artorg.unibe.ch/unibe/portal/fak_medizin/dept_weitere/ins_artorg/content/WEBuseonly_ARTORG_DD3601_eng.gif">
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

liverdata/templates/liverdata/lesion_detail.html
{% extends 'liverdata/base.html' %}


{% block body %}
&nbsp;
<div class="container-fluid patients-container">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <div  class = "well">
        <p style="color:MidnightBlue; font-size:14px; font-weight:bold">Patient - {{ patient.patient_name}} </p>
    </div>
    </div>

    <div class="col-sm-8 text-left">&nbsp;
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th> Nr </th>
              <th> Lesion Name </th>
              <th> Lesion Size </th>
              <th> Lesion Biopsy </th>
              <th> Treatment Details </th>
            </tr>
          </thead>

          <tbody>
            {% if patient.lesion_set.all %}
             {% for lesion in patient.lesion_set.all %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a href='/liverdata/{{ patient.id }}/{{ lesion.id }}/'> {{ lesion.lesiontype }}</a></td>
              <td>{{ lesion.lesion_volume_ml }}  </td>
              <td> {{ lesion.lesion_biopsy}} </td>
              <td><a href="/liverdata/{{ patient.id }}/{{ lesion.id }}/" class="btn btn-primary btn-sm" role="button">View Details</a></td>
            </tr>
            {% endfor %}
          </tbody>
          {% else %}
          <h3> No lesions are available</h3> {% endif %}
        </table>
      </div>
    </div>

    <div class="col-sm-2 sidenav">
      <!-- <div class="well">
        <p>Link</p>
      </div> -->
    </div>
    {% endblock %}

liverdata/templates/liverdata/patient_detail.html
{% extends 'liverdata/base.html' %}


{% block body %}
&nbsp;
<div class="container-fluid patients-container">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <div  class = "well">
        <p style="color:MidnightBlue; font-size:14px; font-weight:bold">Patient - {{ patient.patient_name}} </p>
    </div>
    </div>

    <div class="col-sm-8 text-left">&nbsp;
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th> Nr </th>
              <th> Lesion Name </th>
              <th> Lesion Size </th>
              <th> Lesion Biopsy </th>
              <th> Treatment Details </th>
            </tr>
          </thead>

          <tbody>
            {% if patient.lesion_set.all %}
             {% for lesion in patient.lesion_set.all %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a href="{% url 'liverdata:lesion_detail' lesion.id %}"> {{ lesion.lesiontype }}</a></td>
              <td>{{ lesion.lesion_volume_ml }}  </td>
              <td> {{ lesion.lesion_biopsy}} </td>
              <td><a href="{% url 'liverdata:lesion_detail' lesion.id %}" class="btn btn-primary btn-sm" role="button">View Details</a></td>
            </tr>
            {% endfor %}
          </tbody>
          {% else %}
          <h3> No lesions are available</h3> {% endif %}
        </table>
      </div>
    </div>

    <div class="col-sm-2 sidenav">
      <!-- <div class="well">
        <p>Link</p>
      </div> -->
    </div>
    {% endblock %}

liverdata/templates/liverdata/patient_list.html
{% extends 'liverdata/base.html' %}


{% block body %} {% block title %}
<h2></h2>{% endblock %}
<div class="container-fluid patients-container">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <!-- <div  class = "well">
        <p><a href="#">Link</a></p>
        <p><a href="#">Link</a></p>
        <p><a href="#">Link</a></p>
    </div> -->
  </div>


<div class="col-sm-8 text-left">
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th> Nr </th>
          <th> Name </th>
          <th> Study Institution</th>
          <th> Study Name</th>
          <th> Details </th>
        </tr>
      </thead>

      <tbody>
        {% if all_patients %}
         {% for patient in all_patients %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a href="{% url 'liverdata:patient_detail' patient.id %}">{{ patient.patient_name }}</a></td>
          <td>{{ patient.study_institution}}</td>
          <td>{{ patient.study_name}}</td>
          <td><a href="{% url 'liverdata:patient_detail' patient.id %}" class="btn btn-primary btn-sm" role="button">View Details</a></td>
        </tr>
        {% endfor %}
      </tbody>
      {% else %}
      <h3> No patients are available</h3> {% endif %}
    </table>
  </div>
</div>


    <div class="col-sm-2 sidenav">
      <!-- <div class="well">
        <p>Link</p>
      </div> -->
    </div>
    {% endblock %}

liverdata/templates/liverdata/treatment_detail.html
{% extends 'liverdata/base.html' %}

{% block body %}
&nbsp;
<div class="container-fluid patients-container">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <div class = "well">
        <p style="color:MidnightBlue; font-size:14px; font-weight:bold">Patient - {{ patient.patient_name}} </p>
        <p style="color:MidnightBlue; font-size:14px; font-weight:bold">Lesion - {{ lesion.lesion_name}} </p>
    </div>
    </div>

    <div class="col-sm-8 text-left">&nbsp;
      <div class="table-responsive">
        <table class="table table-striped table-bordered">
          <thead>
            <tr>
              <th> Nr </th>
              <th> Treatment Name </th>
              <th> Treatment Type </th>
              <th> Treatment Date </th>
            </tr>
          </thead>

          <tbody>
            {% if lesion.treatment_set.all %}
             {% for treatment in lesion.treatment_set.all %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ treatment.treatmentname }}</td>
              <td>{{ treatment.treatmentsession }} </td>
              <td>{{ treatment.treatmentsession_date }}</td>
            </tr>
            {% endfor %}
          </tbody>
          {% else %}
          <h3> No treatments are available </h3> {% endif %}
        </table>
      </div>
    </div>

    <div class="col-sm-2 sidenav">
      <!-- <div class="well">
        <p>Link</p>
      </div> -->
    </div>
{% endblock %}